import Image from "next/image";
import Link from "next/link";

const architecture = [
  ["Discover", "Home", "Search", "Services", "Categories"],
  ["Understand", "Service details", "Eligibility", "Requirements", "Fees"],
  ["Complete", "Permit application", "Issue report", "Review", "Confirmation"],
  ["Follow up", "Request number", "Status timeline", "Contact support", "Updates"],
];

const permitFlow = ["Find parking permits", "Check eligibility", "Enter applicant details", "Add vehicle", "Select documents", "Review", "Simulated payment", "Track status"];
const reportFlow = ["Choose issue category", "Enter location", "Describe the problem", "Add optional photo", "Choose contact preference", "Review", "Submit", "Track status"];

const technicalDecisions = [
  ["Task based navigation", "Services are described using resident goals and familiar language instead of requiring people to understand department ownership."],
  ["Requirements before action", "Eligibility, documents, fees, and demonstration boundaries appear before a resident begins a consequential form."],
  ["Stateful guided forms", "Permit and issue journeys keep each step focused while preserving entered values for review and correction."],
  ["Explicit simulation", "Payment, uploads, submission, and status pages demonstrate the experience without claiming real city processing or persistence."],
];

const accessibilityEvidence = [
  ["Keyboard navigation", "Skip links, native buttons, links, inputs, and predictable tab order support pointer free completion."],
  ["Form relationships", "Labels, fieldsets, legends, hints, required states, and grouped choices preserve context through long forms."],
  ["Status communication", "Progress uses numbers, text, position, and state labels so meaning is never communicated by color alone."],
  ["Responsive continuity", "Desktop, tablet, and 375 pixel mobile checks confirm readable forms without horizontal document overflow."],
];

const futureWork = [
  ["Resident research", "Run moderated task sessions for service discovery, permit completion, issue reporting, and status interpretation."],
  ["Persistent application state", "Add authenticated draft saving and secure server persistence while maintaining clear privacy guidance."],
  ["Content governance", "Define ownership, review dates, and publishing workflows for service requirements and eligibility content."],
  ["Automated journey tests", "Add browser based integration coverage for form progression, validation, confirmation, and request tracking."],
];

export default function CivicConnectCaseStudy() {
  return <>
    <a className="caseSkip" href="#caseMain">Skip to case study</a>
    <header className="caseHeader"><Link className="caseWordmark" href="/">Venkat Ankit Gundala</Link><nav aria-label="Case study navigation"><a href="#problem">Problem</a><a href="#process">Process</a><a href="#outcome">Outcome</a></nav><Link className="caseHeaderLink" href="/civicconnect">Open live project →</Link></header>
    <main id="caseMain">
      <section className="caseHero"><div><p className="caseLabel">Product design · Frontend engineering · 2026</p><h1>City services, without the runaround.</h1><p className="caseLead">CivicConnect is a fictional city platform that helps residents find services, complete common tasks, and follow requests through clear and accessible journeys.</p><div className="caseActions"><Link href="/civicconnect">Explore live project →</Link><a href="#problem">Read the case study ↓</a></div></div><div className="caseHeroVisual"><span>CivicConnect</span><strong>What do you need help with today?</strong><div><i>P</i><i>$</i><i>!</i></div><small>Find services · Complete tasks · Track progress</small></div></section>

      <section className="caseFacts"><div><span>Role</span><strong>Product designer and developer</strong></div><div><span>Scope</span><strong>Research assumptions through tested interface</strong></div><div><span>Tools</span><strong>Next.js, React, TypeScript, CSS</strong></div><div><span>Focus</span><strong>Accessibility, forms, responsive systems</strong></div></section>

      <section className="caseSection problemSection" id="problem"><p className="caseNumber">01 · The problem</p><div><h2>Public services are often organized around departments, not resident needs.</h2><div className="caseColumns"><p>Residents may know what they need to accomplish without knowing which department owns the task. Dense navigation, unclear requirements, and disconnected status systems add unnecessary effort.</p><p>The design challenge was to create one credible entry point for discovery, application, reporting, and follow up while keeping complex information understandable.</p></div><aside><strong>Design question</strong><p>How might a city service platform help residents move from a need to a completed task with less uncertainty?</p></aside></div></section>

      <section className="caseSection usersSection"><p className="caseNumber">02 · Users and assumptions</p><div><h2>Designed for residents with different goals, abilities, and levels of confidence.</h2><div className="personaGrid"><article><span>Resident completing a task</span><h3>Needs speed and clarity</h3><p>Wants to understand requirements, finish an application, and know what happens next.</p></article><article><span>Resident reporting a concern</span><h3>Needs a simple path</h3><p>Wants to describe a local problem, provide its location, and receive a trackable request.</p></article><article><span>Resident seeking information</span><h3>Needs strong discovery</h3><p>May start with search, a category, a common task, or a service name.</p></article></div><div className="assumptionNote"><strong>Research status</strong><p>This project began with explicit assumptions based on common public service patterns. No user research or measured usability results are claimed. Formal usability sessions are planned for a later iteration.</p></div></div></section>

      <section className="caseSection civicEvidenceSection"><p className="caseNumber">03 · Product evidence</p><div><h2>One system supports discovery, completion, and follow up.</h2><p className="sectionLead">These captures come from the deployed product. Together they show the service directory, both guided journeys, a status experience, and the narrow screen layout.</p><div className="civicEvidenceGrid"><figure className="civicEvidenceWide"><Image src="/case-studies/civicconnect/services-desktop.png" alt="CivicConnect desktop service directory with search, categories, and service cards" width={1425} height={891} sizes="(max-width: 850px) 100vw, 900px" /><figcaption><strong>Service discovery</strong><span>Search · Categories · Task cards</span></figcaption></figure><figure><Image src="/case-studies/civicconnect/permit-desktop.png" alt="Resident parking permit application showing progress and labeled applicant fields" width={1425} height={891} sizes="(max-width: 850px) 100vw, 580px" /><figcaption><strong>Permit application</strong><span>Guided form · Visible progress</span></figcaption></figure><figure><Image src="/case-studies/civicconnect/report-desktop.png" alt="City issue reporting form showing categories and report progress" width={1425} height={891} sizes="(max-width: 850px) 100vw, 580px" /><figcaption><strong>Issue reporting</strong><span>Category first · Nonemergency guidance</span></figcaption></figure><figure><Image src="/case-studies/civicconnect/status-desktop.png" alt="Parking permit request status showing an under review state and application timeline" width={1425} height={891} sizes="(max-width: 850px) 100vw, 580px" /><figcaption><strong>Request status</strong><span>Timeline · Details · Next step</span></figcaption></figure><figure className="civicEvidenceMobile"><Image src="/case-studies/civicconnect/services-mobile.png" alt="CivicConnect service directory adapted to a narrow mobile screen" width={375} height={812} sizes="(max-width: 520px) 80vw, 280px" /><figcaption><strong>Mobile discovery</strong><span>375 pixel viewport · No page overflow</span></figcaption></figure></div></div></section>

      <section className="caseSection architectureSection" id="process"><p className="caseNumber">04 · Information architecture</p><div><h2>Organize around the resident journey.</h2><p className="sectionLead">The structure moves from discovery to understanding, completion, and follow up. Each stage answers the next question a resident is likely to have.</p><div className="architectureMap">{architecture.map(([stage, ...items], index) => <article key={stage}><span>{String(index + 1).padStart(2, "0")}</span><h3>{stage}</h3><ul>{items.map(item => <li key={item}>{item}</li>)}</ul></article>)}</div></div></section>

      <section className="flowSection"><div className="flowIntro"><p className="caseLabel">Primary journey</p><h2>Resident parking permit</h2><p>The flow reduces uncertainty by presenting eligibility and document requirements before the application begins.</p></div><ol>{permitFlow.map((item, index) => <li key={item}><span>{String(index + 1).padStart(2, "0")}</span><strong>{item}</strong></li>)}</ol><Link href="/civicconnect/services/parking-permits">Try the permit journey →</Link></section>

      <section className="flowSection alternateFlow"><div className="flowIntro"><p className="caseLabel">Secondary journey</p><h2>Report a city issue</h2><p>The reporting flow begins with a recognizable category, then gathers location, detail, contact preference, and confirmation.</p></div><ol>{reportFlow.map((item, index) => <li key={item}><span>{String(index + 1).padStart(2, "0")}</span><strong>{item}</strong></li>)}</ol><Link href="/civicconnect/report">Try the reporting journey →</Link></section>

      <section className="caseSection civicArchitectureSection"><p className="caseNumber">05 · Application architecture</p><div><h2>Separate shared service content from journey specific interaction.</h2><p className="sectionLead">Server rendered discovery pages use a shared service model. Client components own temporary form and tracker state, while route based confirmation and status pages make each outcome directly addressable.</p><div className="civicArchitecture" role="img" aria-label="CivicConnect architecture from shared service content through server rendered discovery and client side journeys to confirmation and status routes"><div><span>01 · Content</span><strong>Service model</strong><small>Categories · Requirements · Actions · Sources</small></div><i aria-hidden="true">→</i><div><span>02 · Experience</span><strong>Server and client views</strong><small>Directory · Details · Guided forms · Tracker</small></div><i aria-hidden="true">→</i><div><span>03 · Outcomes</span><strong>Addressable routes</strong><small>Confirmation · Request status · Official links</small></div></div><div className="prototypeBoundary"><strong>Prototype boundary</strong><p>Application values remain in browser memory. Files are not uploaded, payments are simulated, and no request is sent to a real city system.</p></div></div></section>

      <section className="caseSection systemSection"><p className="caseNumber">06 · Interface system</p><div><h2>A calm visual language for consequential tasks.</h2><div className="systemShowcase"><article className="colorSystem"><h3>Color</h3><div><span><i className="swatch blue" />Civic blue</span><span><i className="swatch teal" />Action teal</span><span><i className="swatch mint" />Support mint</span><span><i className="swatch cream" />Warm canvas</span></div></article><article className="typeSystem"><h3>Type and hierarchy</h3><strong>Clear page titles guide every journey.</strong><p>Body content uses a readable sans serif system with restrained sizes and consistent spacing.</p></article><article className="componentSystem"><h3>Reusable components</h3><div><button>Primary action</button><span className="sampleBadge">Under review</span><label>Visible field label<input placeholder="Helpful input example" /></label></div></article></div></div></section>

      <section className="caseSection civicDecisionSection"><p className="caseNumber">07 · Technical decisions</p><div><h2>Interaction decisions reduce uncertainty before, during, and after a task.</h2><div className="civicDecisionGrid">{technicalDecisions.map(([title, detail], index) => <article key={title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{detail}</p></article>)}</div><div className="civicSourceLinks" aria-label="Relevant CivicConnect source code"><a href="https://github.com/gundalavenkatankit/Portfolio/blob/main/src/app/civicconnect/data.ts" target="_blank" rel="noreferrer">Service model ↗</a><a href="https://github.com/gundalavenkatankit/Portfolio/blob/main/src/app/civicconnect/services/page.tsx" target="_blank" rel="noreferrer">Directory and search ↗</a><a href="https://github.com/gundalavenkatankit/Portfolio/blob/main/src/app/civicconnect/services/parking-permits/apply/permit-application.tsx" target="_blank" rel="noreferrer">Permit journey ↗</a><a href="https://github.com/gundalavenkatankit/Portfolio/blob/main/src/app/civicconnect/report/issue-report.tsx" target="_blank" rel="noreferrer">Issue journey ↗</a><a href="https://github.com/gundalavenkatankit/Portfolio/blob/main/src/app/civicconnect/request-tracker.tsx" target="_blank" rel="noreferrer">Request tracker ↗</a></div></div></section>

      <section className="caseSection accessibilitySection"><p className="caseNumber">08 · Accessibility</p><div><h2>Accessibility shapes the product, not a final checklist.</h2><div className="accessGrid">{accessibilityEvidence.map(([title, detail], index) => <article key={title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{detail}</p></article>)}</div></div></section>

      <section className="caseSection testingSection"><p className="caseNumber">09 · Testing and iteration</p><div><h2>Build, inspect, correct, repeat.</h2><p className="sectionLead">Static checks protect code quality and production compilation. Browser verification covers the resident journeys, document structure, responsive layouts, link destinations, and console behavior.</p><div className="testingGrid"><div><strong>1440 px</strong><span>Desktop layout</span></div><div><strong>768 px</strong><span>Tablet layout</span></div><div><strong>375 px</strong><span>Mobile layout</span></div><div><strong>0</strong><span>Horizontal page overflow</span></div></div><div className="civicTestLayers"><article><span>Code checks</span><h3>Lint and production build</h3><code>npm run lint</code><code>npm run build</code><p>Validate source quality, TypeScript, route generation, and production compilation.</p></article><article><span>Journey checks</span><h3>Browser verification</h3><p>Inspect service search, both guided forms, confirmation routes, status pages, keyboard structure, and mobile reflow.</p><strong>Current gap</strong><p>Dedicated automated browser journey tests are planned and are not claimed as complete.</p></article></div><div className="iterationList"><article><span>Iteration 01</span><h3>Reduced unnecessary interface explanation</h3><p>Removed visible labels and service counts when the surrounding context already made their purpose clear.</p></article><article><span>Iteration 02</span><h3>Protected the demonstration from misleading behavior</h3><p>Added clear notices that files stay local and payment is simulated.</p></article><article><span>Iteration 03</span><h3>Improved mobile continuity</h3><p>Reworked progress indicators, forms, status cards, and the footer for narrow screens.</p></article></div></div></section>

      <section className="caseSection civicLimitationsSection"><p className="caseNumber">10 · Limitations and next steps</p><div><h2>A credible prototype still needs resident evidence and production infrastructure.</h2><div className="caseColumns"><p>The information architecture and interface are based on explicit assumptions rather than interviews or measured usability sessions. No improvement in task completion or resident satisfaction is claimed.</p><p>The demonstration stores no applications, uploads no files, processes no payments, and sends no notifications. Production use would require secure identity, persistence, auditing, privacy controls, and operational content ownership.</p></div><div className="civicFutureGrid">{futureWork.map(([title, detail]) => <article key={title}><h3>{title}</h3><p>{detail}</p></article>)}</div></div></section>

      <section className="caseOutcome" id="outcome"><p className="caseNumber">11 · Outcome</p><h2>A working service platform with two complete resident journeys.</h2><div className="outcomeGrid"><div><strong>3</strong><span>Core public pages</span></div><div><strong>2</strong><span>Complete service journeys</span></div><div><strong>8</strong><span>Steps per journey</span></div><div><strong>2</strong><span>Request status experiences</span></div></div><p>No performance or usability improvement is claimed without measured research. The outcome is a production quality demonstration of information architecture, accessible form design, responsive implementation, and end to end product thinking.</p><Link href="/civicconnect">Explore CivicConnect →</Link></section>

      <section className="learningSection"><p className="caseNumber">12 · What I learned</p><div><h2>Good service design removes uncertainty at every step.</h2><p>Complex flows become more manageable when requirements arrive before action, progress stays visible, and confirmation explains what will happen next. Building the interface also reinforced that accessibility decisions improve clarity for everyone.</p></div></section>
    </main>
    <footer className="caseFooter"><Link className="caseWordmark" href="/">Venkat Ankit Gundala</Link><p>CivicConnect · Case study · 2026</p><Link href="/civicconnect">Open live project →</Link></footer>
  </>;
}
