import Link from "next/link";

const architecture = [
  ["Discover", "Home", "Search", "Services", "Categories"],
  ["Understand", "Service details", "Eligibility", "Requirements", "Fees"],
  ["Complete", "Permit application", "Issue report", "Review", "Confirmation"],
  ["Follow up", "Request number", "Status timeline", "Contact support", "Updates"],
];

const permitFlow = ["Find parking permits", "Check eligibility", "Enter applicant details", "Add vehicle", "Select documents", "Review", "Simulated payment", "Track status"];
const reportFlow = ["Choose issue category", "Enter location", "Describe the problem", "Add optional photo", "Choose contact preference", "Review", "Submit", "Track status"];

export default function CivicConnectCaseStudy() {
  return <>
    <a className="caseSkip" href="#caseMain">Skip to case study</a>
    <header className="caseHeader"><Link className="caseWordmark" href="/">Venkat Ankit Gundala</Link><nav aria-label="Case study navigation"><a href="#problem">Problem</a><a href="#process">Process</a><a href="#outcome">Outcome</a></nav><Link className="caseHeaderLink" href="/civicconnect">Open live project →</Link></header>
    <main id="caseMain">
      <section className="caseHero"><div><p className="caseLabel">Product design · Frontend engineering · 2026</p><h1>City services, without the runaround.</h1><p className="caseLead">CivicConnect is a fictional city platform that helps residents find services, complete common tasks, and follow requests through clear and accessible journeys.</p><div className="caseActions"><Link href="/civicconnect">Explore live project →</Link><a href="#problem">Read the case study ↓</a></div></div><div className="caseHeroVisual"><span>CivicConnect</span><strong>What do you need help with today?</strong><div><i>P</i><i>$</i><i>!</i></div><small>Find services · Complete tasks · Track progress</small></div></section>

      <section className="caseFacts"><div><span>Role</span><strong>Product designer and developer</strong></div><div><span>Scope</span><strong>Research assumptions through tested interface</strong></div><div><span>Tools</span><strong>Next.js, React, TypeScript, CSS</strong></div><div><span>Focus</span><strong>Accessibility, forms, responsive systems</strong></div></section>

      <section className="caseSection problemSection" id="problem"><p className="caseNumber">01 · The problem</p><div><h2>Public services are often organized around departments, not resident needs.</h2><div className="caseColumns"><p>Residents may know what they need to accomplish without knowing which department owns the task. Dense navigation, unclear requirements, and disconnected status systems add unnecessary effort.</p><p>The design challenge was to create one credible entry point for discovery, application, reporting, and follow up while keeping complex information understandable.</p></div><aside><strong>Design question</strong><p>How might a city service platform help residents move from a need to a completed task with less uncertainty?</p></aside></div></section>

      <section className="caseSection usersSection"><p className="caseNumber">02 · Users and assumptions</p><div><h2>Designed for residents with different goals, abilities, and levels of confidence.</h2><div className="personaGrid"><article><span>Resident completing a task</span><h3>Needs speed and clarity</h3><p>Wants to understand requirements, finish an application, and know what happens next.</p></article><article><span>Resident reporting a concern</span><h3>Needs a simple path</h3><p>Wants to describe a local problem, provide its location, and receive a trackable request.</p></article><article><span>Resident seeking information</span><h3>Needs strong discovery</h3><p>May start with search, a category, a common task, or a service name.</p></article></div><div className="assumptionNote"><strong>Research status</strong><p>This project began with explicit assumptions based on common public service patterns. No user research or measured usability results are claimed. Formal usability sessions are planned for a later iteration.</p></div></div></section>

      <section className="caseSection architectureSection" id="process"><p className="caseNumber">03 · Information architecture</p><div><h2>Organize around the resident journey.</h2><p className="sectionLead">The structure moves from discovery to understanding, completion, and follow up. Each stage answers the next question a resident is likely to have.</p><div className="architectureMap">{architecture.map(([stage, ...items], index) => <article key={stage}><span>{String(index + 1).padStart(2, "0")}</span><h3>{stage}</h3><ul>{items.map(item => <li key={item}>{item}</li>)}</ul></article>)}</div></div></section>

      <section className="flowSection"><div className="flowIntro"><p className="caseLabel">Primary journey</p><h2>Resident parking permit</h2><p>The flow reduces uncertainty by presenting eligibility and document requirements before the application begins.</p></div><ol>{permitFlow.map((item, index) => <li key={item}><span>{String(index + 1).padStart(2, "0")}</span><strong>{item}</strong></li>)}</ol><Link href="/civicconnect/services/parking-permits">Try the permit journey →</Link></section>

      <section className="flowSection alternateFlow"><div className="flowIntro"><p className="caseLabel">Secondary journey</p><h2>Report a city issue</h2><p>The reporting flow begins with a recognizable category, then gathers location, detail, contact preference, and confirmation.</p></div><ol>{reportFlow.map((item, index) => <li key={item}><span>{String(index + 1).padStart(2, "0")}</span><strong>{item}</strong></li>)}</ol><Link href="/civicconnect/report">Try the reporting journey →</Link></section>

      <section className="caseSection systemSection"><p className="caseNumber">04 · Interface system</p><div><h2>A calm visual language for consequential tasks.</h2><div className="systemShowcase"><article className="colorSystem"><h3>Color</h3><div><span><i className="swatch blue" />Civic blue</span><span><i className="swatch teal" />Action teal</span><span><i className="swatch mint" />Support mint</span><span><i className="swatch cream" />Warm canvas</span></div></article><article className="typeSystem"><h3>Type and hierarchy</h3><strong>Clear page titles guide every journey.</strong><p>Body content uses a readable sans serif system with restrained sizes and consistent spacing.</p></article><article className="componentSystem"><h3>Reusable components</h3><div><button>Primary action</button><span className="sampleBadge">Under review</span><label>Visible field label<input placeholder="Helpful input example" /></label></div></article></div></div></section>

      <section className="caseSection accessibilitySection"><p className="caseNumber">05 · Accessibility</p><div><h2>Accessibility shapes the product, not a final checklist.</h2><div className="accessGrid"><article><span>01</span><h3>Keyboard access</h3><p>Every journey supports native tab order, visible focus, and a skip link.</p></article><article><span>02</span><h3>Semantic forms</h3><p>Labels, field groups, legends, native validation, and clear input purpose support completion.</p></article><article><span>03</span><h3>More than color</h3><p>Status states combine text, shape, numbering, and color so meaning is never color dependent.</p></article><article><span>04</span><h3>Responsive reading</h3><p>Layouts remain usable at narrow widths without horizontal page overflow.</p></article></div></div></section>

      <section className="caseSection testingSection"><p className="caseNumber">06 · Testing and iteration</p><div><h2>Build, inspect, correct, repeat.</h2><div className="testingGrid"><div><strong>1440 px</strong><span>Desktop layout</span></div><div><strong>768 px</strong><span>Tablet layout</span></div><div><strong>390 px</strong><span>Mobile layout</span></div><div><strong>0</strong><span>Console errors</span></div></div><div className="iterationList"><article><span>Iteration 01</span><h3>Reduced unnecessary interface explanation</h3><p>Removed visible labels and service counts when the surrounding context already made their purpose clear.</p></article><article><span>Iteration 02</span><h3>Protected the demonstration from misleading behavior</h3><p>Added clear notices that files stay local and payment is simulated.</p></article><article><span>Iteration 03</span><h3>Improved mobile continuity</h3><p>Reworked progress indicators, forms, status cards, and the footer for narrow screens.</p></article></div></div></section>

      <section className="caseOutcome" id="outcome"><p className="caseNumber">07 · Outcome</p><h2>A working service platform with two complete resident journeys.</h2><div className="outcomeGrid"><div><strong>3</strong><span>Core public pages</span></div><div><strong>2</strong><span>Complete service journeys</span></div><div><strong>8</strong><span>Steps per journey</span></div><div><strong>2</strong><span>Request status experiences</span></div></div><p>No performance or usability improvement is claimed without measured research. The outcome is a production quality demonstration of information architecture, accessible form design, responsive implementation, and end to end product thinking.</p><Link href="/civicconnect">Explore CivicConnect →</Link></section>

      <section className="learningSection"><p className="caseNumber">08 · What I learned</p><div><h2>Good service design removes uncertainty at every step.</h2><p>Complex flows become more manageable when requirements arrive before action, progress stays visible, and confirmation explains what will happen next. Building the interface also reinforced that accessibility decisions improve clarity for everyone.</p></div></section>
    </main>
    <footer className="caseFooter"><Link className="caseWordmark" href="/">Venkat Ankit Gundala</Link><p>CivicConnect · Case study · 2026</p><Link href="/civicconnect">Open live project →</Link></footer>
  </>;
}
