import Link from "next/link";

const sourceLayers = [
  ["National Weather Service", "Active watches, warnings, and advisories", "Immediate awareness"],
  ["FEMA shelter system", "Registered shelter locations and operational details", "Immediate needs"],
  ["OpenFEMA", "Federal disaster declarations and assistance programs", "Federal status"],
  ["FEMA recovery centers", "Active centers offering recovery guidance", "Recovery support"],
];

const coordinatorFlow = ["Enter a city or postal code", "Resolve the location", "Request official sources", "Normalize different records", "Rank nearby resources", "Present recommended actions"];

const safeguards = [
  ["Source clarity", "Every information type names its official source and preserves a path to the original record."],
  ["Status clarity", "Alerts, declarations, shelters, and recovery centers are never presented as interchangeable signals."],
  ["Unknown values", "Missing accessibility, pet, capacity, and contact fields are labeled unknown instead of being treated as unavailable."],
  ["Travel warning", "Shelter pages remind people to verify operating status and follow local authority instructions before traveling."],
];

export default function ReliefReadyCaseStudy() {
  return <>
    <a className="caseSkip" href="#caseMain">Skip to case study</a>
    <header className="caseHeader"><Link className="caseWordmark" href="/">Venkat Ankit Gundala</Link><nav aria-label="Case study navigation"><a href="#problem">Problem</a><a href="#system">System</a><a href="#testing">Testing</a><a href="#outcome">Outcome</a></nav><Link className="caseHeaderLink" href="/disaster-resource-coordinator">Open live project →</Link></header>
    <main id="caseMain">
      <section className="caseHero reliefCaseHero"><div><p className="caseLabel">Product design · Full stack engineering · 2026</p><h1>Clear information when every minute matters.</h1><p className="caseLead">ReliefReady coordinates official alerts, nearby shelters, federal declarations, and recovery centers around one location so people can understand what is happening and what to do next.</p><div className="caseActions"><Link href="/disaster-resource-coordinator">Explore live project →</Link><a href="#problem">Read the case study ↓</a></div></div><div className="reliefHeroVisual"><div className="visualStatus"><span>ReliefReady</span><strong>Official sources</strong></div><h2>My area</h2><p>One location. Four coordinated information systems.</p><div className="visualResultGrid"><span>Alerts</span><span>Shelters</span><span>Declarations</span><span>Recovery</span></div><small>Verify information before taking action</small></div></section>

      <section className="caseFacts reliefFacts"><div><span>Role</span><strong>Product designer and full stack developer</strong></div><div><span>Data</span><strong>Four official public information systems</strong></div><div><span>Tools</span><strong>Next.js, React, TypeScript, public APIs</strong></div><div><span>Focus</span><strong>Trust, accessibility, location, resilience</strong></div></section>

      <section className="caseSection problemSection" id="problem"><p className="caseNumber">01 · The problem</p><div><h2>Disaster information is credible but fragmented.</h2><div className="caseColumns"><p>A person may need to check a weather alert, locate a shelter, understand federal assistance, and find a recovery center. Each task can begin in a different government system with different terminology and record structures.</p><p>The challenge was not simply to collect links. It was to coordinate distinct official sources without blurring what each one means or presenting uncertain information as guaranteed.</p></div><aside><strong>Design question</strong><p>How might one location based experience help people find trusted disaster information while preserving the meaning and limitations of every source?</p></aside></div></section>

      <section className="caseSection reliefUsers"><p className="caseNumber">02 · User needs</p><div><h2>Urgency changes how information should be organized.</h2><div className="personaGrid"><article><span>Immediate awareness</span><h3>What affects my area now?</h3><p>People need current alerts, clear severity language, issuing authority, and direct official guidance.</p></article><article><span>Immediate needs</span><h3>Where can I find shelter?</h3><p>People need nearby options, operating status, accessibility information, capacity, and directions.</p></article><article><span>Recovery</span><h3>What assistance is available?</h3><p>People need to distinguish a federal declaration from a live warning and locate appropriate recovery support.</p></article></div><div className="assumptionNote"><strong>Safety boundary</strong><p>ReliefReady is an informational portfolio project. It does not replace 911, emergency officials, evacuation orders, or direct verification with a shelter.</p></div></div></section>

      <section className="caseSection sourceSection" id="system"><p className="caseNumber">03 · Source strategy</p><div><h2>Use each official system for the question it can answer.</h2><p className="sectionLead">The product keeps live hazards, shelter records, federal status, and recovery services separate, then coordinates them through a shared location.</p><div className="sourceTable" role="table" aria-label="Official information sources"><div className="sourceRow sourceHeader" role="row"><span role="columnheader">Source</span><span role="columnheader">Information</span><span role="columnheader">User need</span></div>{sourceLayers.map(row => <div className="sourceRow" role="row" key={row[0]}>{row.map(item => <span role="cell" key={item}>{item}</span>)}</div>)}</div></div></section>

      <section className="reliefFlow"><div><p className="caseLabel">Location coordinator</p><h2>One search becomes a structured area summary.</h2><p>The server resolves a location, requests independent public sources, normalizes their records, and returns a readable summary with direct next steps.</p></div><ol>{coordinatorFlow.map((item, index) => <li key={item}><span>{String(index + 1).padStart(2, "0")}</span><strong>{item}</strong></li>)}</ol><Link href="/disaster-resource-coordinator/my-area">Try My Area →</Link></section>

      <section className="caseSection shelterSection"><p className="caseNumber">04 · Shelter discovery</p><div><h2>Finding a shelter requires more than matching text.</h2><div className="shelterStory"><article><span>01</span><h3>Resolve the search</h3><p>City and postal code searches become geographic coordinates while retaining the selected state.</p></article><article><span>02</span><h3>Rank by proximity</h3><p>When there is no exact postal match, valid FEMA locations are ordered from nearest to farthest.</p></article><article><span>03</span><h3>Compare details</h3><p>Cards expose status, address, capacity, accessibility, pets, generator information, and record detail.</p></article><article><span>04</span><h3>Review manageable results</h3><p>Ten results appear per page with equal navigation controls and a centered page count.</p></article></div><Link className="sectionAction" href="/disaster-resource-coordinator/shelters">Open Shelter Finder →</Link></div></section>

      <section className="caseSection accessibilitySection reliefSafety"><p className="caseNumber">05 · Trust and accessibility</p><div><h2>Safe communication requires visible uncertainty.</h2><div className="accessGrid">{safeguards.map(([title, detail], index) => <article key={title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{detail}</p></article>)}</div></div></section>

      <section className="caseSection testingSection" id="testing"><p className="caseNumber">06 · Testing</p><div><h2>Stable logic is separated from changing public data.</h2><p className="sectionLead">Deterministic tests validate location and ranking behavior locally. A smaller live contract suite checks that the running application can still communicate with external services.</p><div className="testingGrid reliefTesting"><div><strong>716</strong><span>Washington postal codes validated</span></div><div><strong>3</strong><span>Deterministic shelter tests</span></div><div><strong>10</strong><span>Shelter cards per page</span></div><div><strong>4</strong><span>Official source systems coordinated</span></div></div><div className="iterationList"><article><span>Data behavior</span><h3>Nearest results replace empty dead ends</h3><p>A valid location can still receive useful nearby results when no shelter shares the exact city or postal code.</p></article><article><span>Source behavior</span><h3>Official alert links open readable pages</h3><p>Users are directed to Weather.gov presentation pages instead of raw machine readable API records.</p></article><article><span>Interface behavior</span><h3>Pagination remains balanced and accessible</h3><p>Previous and Next controls share the same size, page position remains clear, and mouse interaction does not leave distracting focus treatment.</p></article></div></div></section>

      <section className="caseSection limitationsSection"><p className="caseNumber">07 · Limitations</p><div><h2>Public data can be incomplete, delayed, or operationally uncertain.</h2><div className="caseColumns"><p>FEMA shelter records may represent registered locations that are closed, and fields such as capacity, phone, accessibility, and pets may be unknown. The interface does not invent missing answers.</p><p>There is no single open national source for every local evacuation order, road closure, or community resource. ReliefReady prioritizes verified national systems and links users back to official authorities.</p></div></div></section>

      <section className="caseOutcome reliefOutcome" id="outcome"><p className="caseNumber">08 · Outcome</p><h2>A working coordinator for urgent information and recovery support.</h2><div className="outcomeGrid"><div><strong>1</strong><span>Unified location search</span></div><div><strong>4</strong><span>Coordinated information types</span></div><div><strong>5</strong><span>Shelter comparison filters</span></div><div><strong>716</strong><span>Postal code cases tested</span></div></div><p>The result demonstrates public API integration, server side normalization, geospatial ranking, resilient interface states, automated testing, responsive design, and careful communication for a consequential domain. No emergency outcome or usability improvement is claimed without field research.</p><Link href="/disaster-resource-coordinator">Explore ReliefReady →</Link></section>

      <section className="learningSection"><p className="caseNumber">09 · What I learned</p><div><h2>Trust depends on preserving context, not only displaying data.</h2><p>In a disaster product, an accurate record can still be misleading if its source, freshness, status, or limitations are unclear. The strongest design decisions make uncertainty visible and keep the route to the official authority close to every action.</p></div></section>
    </main>
    <footer className="caseFooter"><Link className="caseWordmark" href="/">Venkat Ankit Gundala</Link><p>ReliefReady · Case study · 2026</p><Link href="/disaster-resource-coordinator">Open live project →</Link></footer>
  </>;
}
