import Image from "next/image";
import Link from "next/link";

const sourceLayers = [
  ["National Weather Service", "Active watches, warnings, and advisories", "Immediate awareness"],
  ["FEMA shelter system", "Registered shelter locations and operational details", "Immediate needs"],
  ["OpenFEMA", "Federal disaster declarations and assistance programs", "Federal status"],
  ["FEMA recovery centers", "Active centers offering recovery guidance", "Recovery support"],
];

const coordinatorFlow = ["Enter a city or postal code", "Resolve the location", "Request official sources", "Normalize different records", "Rank nearby resources", "Present recommended actions"];

const safeguards = [
  ["Source clarity", "Every information type names its official source and preserves a path to the original record."],
  ["Status clarity", "Alerts, declarations, shelters, and recovery centers are never presented as interchangeable signals."],
  ["Unknown values", "Missing accessibility, pet, capacity, and contact fields are labeled unknown instead of being treated as unavailable."],
  ["Travel warning", "Shelter pages remind people to verify operating status and follow local authority instructions before traveling."],
];

const technicalDecisions = [
  ["Server mediated public data", "Next.js route handlers request external services so validation, caching, error mapping, and source specific behavior stay outside the interface."],
  ["Shared normalized records", "Different government fields become consistent alert, shelter, declaration, and recovery center models before they reach a page."],
  ["Progressive fallback", "The interface preserves useful navigation, source links, and honest empty states when a public system is slow or unavailable."],
  ["Geographic ranking", "Coordinate based distance calculation ranks valid shelter geometry instead of relying only on exact text matches."],
];

const accessibilityChecks = [
  ["Keyboard paths", "Skip links, native controls, logical tab order, and visible keyboard focus support navigation without a pointer."],
  ["Semantic structure", "Headings, landmarks, labels, field groups, status regions, terms, and definitions communicate relationships to assistive technology."],
  ["Readable uncertainty", "Text labels communicate unknown values and operating status without depending on color alone."],
  ["Responsive continuity", "Desktop and 375 pixel mobile checks confirm the page reflows without horizontal document overflow."],
];

const futureWork = [
  ["Local emergency sources", "Add a curated registry of state and county emergency management feeds without presenting coverage as universal."],
  ["Saved locations", "Let people store an area on their device and return directly to its coordinated summary."],
  ["Freshness indicators", "Expose source retrieval time and clearer stale data behavior for every information type."],
  ["Field research", "Test comprehension, urgency, and task completion with residents and emergency management professionals."],
];

export default function ReliefReadyCaseStudy() {
  return <>
    <a className="caseSkip" href="#caseMain">Skip to case study</a>
    <header className="caseHeader"><Link className="caseWordmark" href="/">Venkat Ankit Gundala</Link><nav aria-label="Case study navigation"><a href="#problem">Problem</a><a href="#system">System</a><a href="#testing">Testing</a><a href="#outcome">Outcome</a></nav><Link className="caseHeaderLink" href="/disaster-resource-coordinator">Open live project →</Link></header>
    <main id="caseMain">
      <section className="caseHero reliefCaseHero"><div><p className="caseLabel">Product design · Full stack engineering · 2026</p><h1>Clear information when every minute matters.</h1><p className="caseLead">ReliefReady coordinates official alerts, nearby shelters, federal declarations, and recovery centers around one location so people can understand what is happening and what to do next.</p><div className="caseActions"><Link href="/disaster-resource-coordinator">Explore live project →</Link><a href="#problem">Read the case study ↓</a></div></div><div className="reliefHeroVisual"><div className="visualStatus"><span>ReliefReady</span><strong>Official sources</strong></div><h2>My area</h2><p>One location. Four coordinated information systems.</p><div className="visualResultGrid"><span>Alerts</span><span>Shelters</span><span>Declarations</span><span>Recovery</span></div><small>Verify information before taking action</small></div></section>

      <section className="caseFacts reliefFacts"><div><span>Role</span><strong>Product designer and full stack developer</strong></div><div><span>Data</span><strong>Four official public information systems</strong></div><div><span>Tools</span><strong>Next.js, React, TypeScript, public APIs</strong></div><div><span>Focus</span><strong>Trust, accessibility, location, resilience</strong></div></section>

      <section className="caseSection problemSection" id="problem"><p className="caseNumber">01 · The problem</p><div><h2>Disaster information is credible but fragmented.</h2><div className="caseColumns"><p>A person may need to check a weather alert, locate a shelter, understand federal assistance, and find a recovery center. Each task can begin in a different government system with different terminology and record structures.</p><p>The challenge was not simply to collect links. It was to coordinate distinct official sources without blurring what each one means or presenting uncertain information as guaranteed.</p></div><aside><strong>Design question</strong><p>How might one location based experience help people find trusted disaster information while preserving the meaning and limitations of every source?</p></aside></div></section>

      <section className="caseSection reliefUsers"><p className="caseNumber">02 · User needs</p><div><h2>Urgency changes how information should be organized.</h2><div className="personaGrid"><article><span>Immediate awareness</span><h3>What affects my area now?</h3><p>People need current alerts, clear severity language, issuing authority, and direct official guidance.</p></article><article><span>Immediate needs</span><h3>Where can I find shelter?</h3><p>People need nearby options, operating status, accessibility information, capacity, and directions.</p></article><article><span>Recovery</span><h3>What assistance is available?</h3><p>People need to distinguish a federal declaration from a live warning and locate appropriate recovery support.</p></article></div><div className="assumptionNote"><strong>Safety boundary</strong><p>ReliefReady is an informational portfolio project. It does not replace 911, emergency officials, evacuation orders, or direct verification with a shelter.</p></div></div></section>

      <section className="caseSection evidenceSection"><p className="caseNumber">03 · Product evidence</p><div><h2>A working interface across urgent tasks and screen sizes.</h2><p className="sectionLead">These captures come from the deployed product. They show the main coordination experience, real FEMA shelter records, visible verification guidance, and the responsive mobile layout.</p><div className="productEvidence"><figure className="evidenceWide"><Image src="/case-studies/reliefready/dashboard-desktop.png" alt="ReliefReady desktop dashboard showing the selected Texas area and emergency guidance" width={1425} height={891} sizes="(max-width: 850px) 100vw, 900px" /><figcaption><strong>Area dashboard</strong><span>Desktop · Coordinated entry point</span></figcaption></figure><figure><Image src="/case-studies/reliefready/shelter-results-desktop.png" alt="ReliefReady shelter finder showing official FEMA records and comparison filters" width={1425} height={891} sizes="(max-width: 850px) 100vw, 600px" /><figcaption><strong>Shelter results</strong><span>Official records · Filterable cards</span></figcaption></figure><figure className="evidenceMobile"><Image src="/case-studies/reliefready/dashboard-mobile.png" alt="ReliefReady dashboard adapted to a narrow mobile screen" width={375} height={812} sizes="(max-width: 520px) 80vw, 300px" /><figcaption><strong>Mobile continuity</strong><span>375 pixel viewport · No page overflow</span></figcaption></figure></div></div></section>

      <section className="caseSection sourceSection" id="system"><p className="caseNumber">04 · Source strategy</p><div><h2>Use each official system for the question it can answer.</h2><p className="sectionLead">The product keeps live hazards, shelter records, federal status, and recovery services separate, then coordinates them through a shared location.</p><div className="sourceTable" role="table" aria-label="Official information sources"><div className="sourceRow sourceHeader" role="row"><span role="columnheader">Source</span><span role="columnheader">Information</span><span role="columnheader">User need</span></div>{sourceLayers.map(row => <div className="sourceRow" role="row" key={row[0]}>{row.map(item => <span role="cell" key={item}>{item}</span>)}</div>)}</div></div></section>

      <section className="caseSection architectureEvidence"><p className="caseNumber">05 · Architecture</p><div><h2>Keep public data complexity behind stable product boundaries.</h2><p className="sectionLead">The browser interacts with typed product views. Server routes own external requests and translate each public system into consistent records, errors, and cache behavior.</p><div className="architectureDiagram" role="img" aria-label="Architecture flow from responsive product views through Next.js server routes to four official public data systems"><div><span>01 · Experience</span><strong>Responsive React views</strong><small>Dashboard · Search · Detail pages</small></div><i aria-hidden="true">→</i><div><span>02 · Coordination</span><strong>Next.js server routes</strong><small>Validate · Normalize · Cache · Map errors</small></div><i aria-hidden="true">→</i><div className="sourceNode"><span>03 · Official systems</span><strong>NWS · FEMA · OpenFEMA</strong><small>Alerts · Shelters · Declarations · Recovery</small></div></div><div className="architectureNotes"><p><strong>Location context</strong> State, city, postal code, and coordinates remain explicit through each request.</p><p><strong>Failure isolation</strong> One unavailable source does not redefine or fabricate the state of another source.</p></div></div></section>

      <section className="reliefFlow"><div><p className="caseLabel">Location coordinator</p><h2>One search becomes a structured area summary.</h2><p>The server resolves a location, requests independent public sources, normalizes their records, and returns a readable summary with direct next steps.</p></div><ol>{coordinatorFlow.map((item, index) => <li key={item}><span>{String(index + 1).padStart(2, "0")}</span><strong>{item}</strong></li>)}</ol><Link href="/disaster-resource-coordinator/my-area">Try My Area →</Link></section>

      <section className="caseSection decisionSection"><p className="caseNumber">06 · Technical decisions</p><div><h2>Design choices connect trust, resilience, and maintainability.</h2><div className="decisionGrid">{technicalDecisions.map(([title, detail], index) => <article key={title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{detail}</p></article>)}</div><div className="sourceLinks" aria-label="Relevant source code"><a href="https://github.com/gundalavenkatankit/Portfolio/blob/main/src/app/api/disaster-shelters/route.ts" target="_blank" rel="noreferrer">Shelter API route ↗</a><a href="https://github.com/gundalavenkatankit/Portfolio/blob/main/src/app/disaster-resource-coordinator/shelters/shelter-finder.tsx" target="_blank" rel="noreferrer">Shelter interface ↗</a><a href="https://github.com/gundalavenkatankit/Portfolio/blob/main/src/app/disaster-resource-coordinator/disaster-dashboard.tsx" target="_blank" rel="noreferrer">Dashboard interface ↗</a></div></div></section>

      <section className="caseSection shelterSection"><p className="caseNumber">07 · Shelter discovery</p><div><h2>Finding a shelter requires more than matching text.</h2><div className="shelterStory"><article><span>01</span><h3>Resolve the search</h3><p>City and postal code searches become geographic coordinates while retaining the selected state.</p></article><article><span>02</span><h3>Rank by proximity</h3><p>When there is no exact postal match, valid FEMA locations are ordered from nearest to farthest.</p></article><article><span>03</span><h3>Compare details</h3><p>Cards expose status, address, capacity, accessibility, pets, generator information, and record detail.</p></article><article><span>04</span><h3>Review manageable results</h3><p>Ten results appear per page with equal navigation controls and a centered page count.</p></article></div><Link className="sectionAction" href="/disaster-resource-coordinator/shelters">Open Shelter Finder →</Link></div></section>

      <section className="caseSection accessibilitySection reliefSafety"><p className="caseNumber">08 · Trust and accessibility</p><div><h2>Safe communication requires visible uncertainty.</h2><div className="accessGrid">{safeguards.map(([title, detail], index) => <article key={title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{detail}</p></article>)}</div><h3 className="evidenceSubheading">Implementation checks</h3><div className="accessibilityEvidence">{accessibilityChecks.map(([title, detail]) => <article key={title}><strong>{title}</strong><p>{detail}</p></article>)}</div></div></section>

      <section className="caseSection testingSection" id="testing"><p className="caseNumber">09 · Testing</p><div><h2>Stable logic is separated from changing public data.</h2><p className="sectionLead">The Node test runner validates location and ranking behavior without depending on a live service. A separate contract script checks communication with the running application and FEMA data when explicitly requested.</p><div className="testingGrid reliefTesting"><div><strong>716</strong><span>Washington postal codes validated</span></div><div><strong>3</strong><span>Deterministic shelter tests</span></div><div><strong>10</strong><span>Shelter cards per page</span></div><div><strong>4</strong><span>Official source systems coordinated</span></div></div><div className="testLayers"><article><span>Local suite</span><h3>Fast and deterministic</h3><code>npm test</code><p>Validates postal search routing, nearest geometry ordering for 98121, and state retention for city searches.</p></article><article><span>Live contract</span><h3>Explicit external check</h3><code>npm run test:shelters:live</code><p>Requires the application server and confirms that the public data boundary still responds with the expected contract.</p></article></div><div className="iterationList"><article><span>Data behavior</span><h3>Nearest results replace empty dead ends</h3><p>A valid location can still receive useful nearby results when no shelter shares the exact city or postal code.</p></article><article><span>Source behavior</span><h3>Official alert links open readable pages</h3><p>Users are directed to Weather.gov presentation pages instead of raw machine readable API records.</p></article><article><span>Interface behavior</span><h3>Pagination remains balanced and accessible</h3><p>Previous and Next controls share the same size, page position remains clear, and mouse interaction does not leave distracting focus treatment.</p></article></div><div className="sourceLinks"><a href="https://github.com/gundalavenkatankit/Portfolio/blob/main/tests/shelter-search.test.mjs" target="_blank" rel="noreferrer">Read deterministic tests ↗</a><a href="https://github.com/gundalavenkatankit/Portfolio/blob/main/scripts/verify-shelter-live.mjs" target="_blank" rel="noreferrer">Read live contract script ↗</a></div></div></section>

      <section className="caseSection limitationsSection"><p className="caseNumber">10 · Limitations and next steps</p><div><h2>Public data can be incomplete, delayed, or operationally uncertain.</h2><div className="caseColumns"><p>FEMA shelter records may represent registered locations that are closed, and fields such as capacity, phone, accessibility, and pets may be unknown. The interface does not invent missing answers.</p><p>There is no single open national source for every local evacuation order, road closure, or community resource. ReliefReady prioritizes verified national systems and links users back to official authorities.</p></div><div className="futureGrid">{futureWork.map(([title, detail]) => <article key={title}><h3>{title}</h3><p>{detail}</p></article>)}</div></div></section>

      <section className="caseOutcome reliefOutcome" id="outcome"><p className="caseNumber">11 · Outcome</p><h2>A working coordinator for urgent information and recovery support.</h2><div className="outcomeGrid"><div><strong>1</strong><span>Unified location search</span></div><div><strong>4</strong><span>Coordinated information types</span></div><div><strong>5</strong><span>Shelter comparison filters</span></div><div><strong>716</strong><span>Postal code cases tested</span></div></div><p>The result demonstrates public API integration, server side normalization, geospatial ranking, resilient interface states, automated testing, responsive design, and careful communication for a consequential domain. No emergency outcome or usability improvement is claimed without field research.</p><Link href="/disaster-resource-coordinator">Explore ReliefReady →</Link></section>

      <section className="learningSection"><p className="caseNumber">12 · What I learned</p><div><h2>Trust depends on preserving context, not only displaying data.</h2><p>In a disaster product, an accurate record can still be misleading if its source, freshness, status, or limitations are unclear. The strongest design decisions make uncertainty visible and keep the route to the official authority close to every action.</p></div></section>
    </main>
    <footer className="caseFooter"><Link className="caseWordmark" href="/">Venkat Ankit Gundala</Link><p>ReliefReady · Case study · 2026</p><Link href="/disaster-resource-coordinator">Open live project →</Link></footer>
  </>;
}
